import discord
from discord.ext import commands
import colorama
from colorama import Fore
import asyncio
from webserver import keep_alive


import os

#-----SETUP-----#

prefix = "$$"

#use the .env feature to hide your token


keep_alive()
token = os.getenv("token")

#---------------#

bot = commands.Bot(command_prefix=prefix,
                   help_command=None,
                   case_insensitive=True,
                   self_bot=True)






@bot.command()
async def help(ctx):
    embed = discord.Embed(
        title="Help",
        color=435436,
        description=
        f"{prefix}autodank**\npls fish, pls dig, pls hunt, pls beg and pls dep all seconds.\n\n**{prefix}stopautodank**\nstops stopsautodank.\n\n**{prefix}banbypass**\n Bypasses dankmember compltely:✅ \n It's also safe to use` \n\n Made by [funnygamer2.OYT]/"
    )
    embed.set_thumbnail(
        url=
        "https://c.tenor.com/rvYiscAk_kAAAAAC/anime-welcome.gif"
    )
    await ctx.send(embed=embed)


@bot.command(pass_context=True)
async def autodank(ctx):
    await ctx.message.delete()
    await ctx.send('auto Dank  is now **enabled**!')
    global dmcs
    dmcs = True
    while dmcs:
        async with ctx.typing():
            await asyncio.sleep(5)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(1800)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(7200)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(45)
            await ctx.send('pls fish')
            print(f"{Fore.GREEN}succefully sent pls fish")
            await asyncio.sleep(1)
            await ctx.send('pls dig')
            print(f"{Fore.GREEN}succefully sent pls dig")
            await asyncio.sleep(1)
            await ctx.send('pls hunt')
            print(f"{Fore.GREEN}succefully sent pls hunt")
            await ctx.send('pls beg')
            print(f"{Fore.GREEN}succefully sent pls beg")
            await asyncio.sleep(1)
            await ctx.send('pls dep all')
            print(f"{Fore.GREEN}succefully sent pls dep all")
            await asyncio.sleep(14400)

            
            
            
keep_alive()
bot.run(os.getenv('token'), bot=False)
